### ISSUE TITLE
Top issues for TPAC 2023 (if any!)

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/audio-session#19]
(writing as co-chair as we planning for TPAC)

Any priority issues we need to discuss face-to-face during TPAC in September? If so, please list them here and we can add them to our agenda. We have allocated a bit of time to this spec during the meeting if we need it.

**Comment by chrisn** [comment]
From @alastor0325:
* https://github.com/w3c/audio-session/issues/1 - The explainer says "The Audio Session API helps to close the gap with platforms that have audio session/audio focus such as Android and iOS". Should we also consider platforms without mandatory audio focus management, eg. Windows, Linux in the v1 spec?

**Comment by chrisn** [comment]
@youennf Is there anything you want to add to the agenda?
