### ISSUE TITLE
There are two sections called Audio Session States

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/audio-session#21]
I think §2.1 should probably be called Audio Session Type.

**Comment by youennf** [comment]
Right, this is taken care of in https://youennf.github.io/audio-session/ amongst other things.

**Comment by nigelmegitt** [comment]
Thanks @youennf I haven't been watching this activity very closely, and the existence of a second Editor's Draft was not obvious to me. It would probably be more helpful to keep a single ED in the place indicated in the spec, if that wouldn't cause other difficulties.

>Plan is to upstream those changes progressively.

At the risk of getting into a misplaced "working modes" discussion, I'd suggest, if they're editorial, just do it, and if they're substantive, open issues and corresponding pull requests, so the WG can easily track and comment on the proposals.

**Comment by youennf** [comment]
> the existence of a second Editor's Draft was not obvious to me

It is not a second editor's draft, I have been working on my branch since last week on this draft.

I am talking with others to see what the best way to upstream the changes.

> if they're substantive, open issues and corresponding pull requests, so the WG can easily track and comment on the proposals.

At TPAC, we agreed on the direction for the issues that these changes are addressing.
But sometimes, TPAC discussions do not go as detailed as what a PR is doing...

I agree we should sort this out quickly, hopefully during this week.

**Comment by nigelmegitt** [comment]
>It is not a second editor's draft, I have been working on my branch since last week on this draft.

Forgive my misunderstanding, I saw that one of the Editor's had their own Draft somewhere else and assumed that made it an Editor's Draft! If it walks like a duck, quacks like a duck, etc. 

Glad that it's a temporary situation.

**Comment by youennf** [comment]
@nigelmegitt, https://github.com/w3c/audio-session/pull/30 will fix the typo you spotted.
Thanks for looking at this spec by the way. I'll probably ping you again when the upstream is done in the hope you can do another review at the more complete spec.

**Comment by youennf** [comment]
Closing this issue now that the upstream has been done.
Please have a look at the latest spec version if you have some time. It probably needs some more ironing.
