### ISSUE TITLE
Should we change the repo/spec name?

### ISSUE THREAD

**Issue by youennf** [w3c/audio-session#9]
Audio focus current name is scoping down a bit the scope of this API to who is playing audio.
An important part of the API is to also be able to influence how the audio is played, via the category (play-and-record).
We might further widen the scope of this API in the future, say if we want to add routine capacities (which speaker to use for instance).

Would something more general like 'audio session' be suitable?
FWIW, the latest version of the explainer is currently mainly using 'audio session'

**Comment by youennf** [comment]
@alastor0325, @steimelchrome, @tguilbert-google, thoughts?

**Comment by tguilbert-google** [comment]
For "Audio Session" I am deferring to @steimelchrome's opinion.

> [...] if we want to add routine capacities (which speaker to use for instance).

Is this different than `setSinkId()`?

Other names to consider (or not):

- Audio Controller
- Audio Flow
- Audio Router

**Comment by youennf** [comment]
> Is this different than `setSinkId()`?

It could be the same, for instance serve as the default sinkId to all audio renderers of the page without an explicitly set sinkId. Or it could be similar to existing OS concepts like AVAudioSession RouteSharingPolicy.

**Comment by steimelchrome** [comment]
Regarding "influencing how the audio is played": isn't that just influencing how the playback interacts with other playback, which is what audio focus is? Though I'm not actually sure I know what "play-and-record" is supposed to do.

That said, I don't have particularly strong feelings on the naming of it. The main concern I can think of is that it could get confusing to have both "media session" and "audio session" APIs that do different things, but that's probably not a big deal

**Comment by alastor0325** [comment]
As the most part of this API are targeting how to handle audio competing between different types, `Audio Focus` is still the best naming I'd choose, `Audio Session` also sounds not too bad to me. `Audio Router` seems too far from the current topic we're going to address, and `Audio Flow/Audio Controller` are pretty general, which might not reflect the goal of this API clearly?

But to be clear I don't have a strong opinion upon naming. Just want it to reflect the goal of API as much as possible.

**Comment by chrisn** [comment]
Commenting with my chair hat off.

> The main concern I can think of is that it could get confusing to have both "media session" and "audio session" APIs that do different things, but that's probably not a big deal

I agree, this was my initial reaction too. Possibly confusing but may not be a huge concern.

> Just want it to reflect the goal of API as much as possible.

I agree, so have a slight preference towards Audio Focus, which I think better communicates the goal.

Would the proposed API still make sense renamed to `AudioFocus`, `AudioFocusType`, and `AudioFocusState`? It seems OK...?

**Comment by youennf** [comment]
Some important use cases we know of for this API are more related to how audio is rendered than to how focus is managed, for instance:
- on iOS `play-and-record` will trigger a different volume level than `playback` and applications might want to set `play-and-record` in advance so that the volume level does not change dynamically when starting to capture microphone.
- some applications use web audio for mixing music and they might set the category to `playback` so that the volume level will not be set to zero when the device is in silence mode like would be the case with `transient`.

The name `AudioFocus` does not seem super well aligned with what these web apps will do with this API.
If we plan to extend this API (say routing API, or the ability to put audio players in groups that should be played in common), the term `AudioFocus` might feel more and more restrictive.

**Comment by chrisn** [comment]
Thanks @youennf, this makes sense. @alastor0325 what do you think?

**Comment by alastor0325** [comment]
Sure, I'm good with the change of using `Audio Session`. The only concern which almost everyone mentions is too similar with `Media Session`, but that is probably not a big deal.

**Comment by chrisn** [comment]
In the [Media WG meeting on 14 Feb 2023](https://www.w3.org/2023/02/14-mediawg-minutes.html)  we agreed on Audio Session.
